Added the recv_tos socket option
rust-lang/socket2 pull request #299
Opened 2022-04-22 09:18 UTC by JoNil

2022-04-22 10:40 UTC, Thomasdezeeuw requested changes
The addition sounds good, but this needs tests and Windows support (see https://docs.microsoft.com/en-us/windows/win32/winsock/ipproto-ip-socket-options).

2022-04-22 10:40 UTC, Thomasdezeeuw commented on src/sys/unix.rs
> +pub(crate) use libc::IP_RECVTOS;
I think this `cfg` is the same as the one for `IP_TOS`, can you merge the two.

2022-04-25 13:12 UTC, JoNil commented
I didn't find the IP_RECVTOS symbol in winapi-rs. Does anyone know if it is supported there and is just not exposed?

2022-04-25 13:29 UTC, Thomasdezeeuw commented
> I didn't find the IP_RECVTOS symbol in winapi-rs. Does anyone know if it is supported there and is just not exposed?

I can't find it either.  Perhaps we should move to `windows_sys` (it has it: https://docs.rs/windows-sys/latest/windows_sys/Win32/Networking/WinSock/constant.IP_RECVTOS.html), but that's a larger topic. For now you can remove Window support and we'll open issue to add it later.

2022-04-25 13:56 UTC, JoNil commented
In the last commit i added windows the the cfg so that it is not included :)

2022-04-26 09:56 UTC, Thomasdezeeuw approved these changes

2022-04-26 09:57 UTC, merged

2022-04-26 09:57 UTC, Thomasdezeeuw commented
Thanks @JoNil.