feat: Add UDP GRO option
rust-lang/socket2 pull request #536
Opened 2024-10-21 12:41 UTC by XAMPPRocky

Allows setting UDP_GRO on the socket.

https://www.man7.org/linux/man-pages/man7/udp.7.html

> Enables UDP receive offload.  If enabled, the socket may
              receive multiple datagrams worth of data as a single large
              buffer, together with a cmsg(3) that holds the segment
              size.  This option is the inverse of segmentation offload.
              It reduces receive cost by handling multiple datagrams
              worth of data as a single large packet in the kernel
              receive path, even when that exceeds MTU.  This option
              should not be used in code intended to be portable.

2024-10-24 20:09 UTC, Thomasdezeeuw requested changes
Since this Linux only, can you put in the sys/unix.rs file: https://github.com/rust-lang/socket2/blob/3a938932829ea6ee3025d2d7a86c7b095c76e6c3/src/sys/unix.rs#L763

Could also you make sure it's order by option name.

Can you add the appropriate attributes, e.g. see https://github.com/rust-lang/socket2/blob/3a938932829ea6ee3025d2d7a86c7b095c76e6c3/src/sys/unix.rs#L791-L795

Finally can you add a test? A simple set and get test is sufficient, see https://github.com/rust-lang/socket2/blob/3a938932829ea6ee3025d2d7a86c7b095c76e6c3/tests/socket.rs#L1357

2024-11-07 14:31 UTC, XAMPPRocky commented
@Thomasdezeeuw Thank you, I've implemented your feedback, the only thing I wasn't 100% sure on was "Could also you make sure it's order by option name." let me know if I need to make more changes

2024-11-21 12:24 UTC, Thomasdezeeuw approved these changes

2024-11-21 12:24 UTC, Thomasdezeeuw commented
Thanks @XAMPPRocky

2025-05-24 10:23 UTC, XAMPPRocky commented
Hey, yeah my initial need for the option isn't needed as the project I was using it in now uses XDP sockets which bypass this setting. I'lll try to mixup the PR next week though.

2026-02-13 11:26 UTC, Thomasdezeeuw commented
Closing this due to inactivity.

2026-02-13 11:26 UTC, closed without merging